### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by TeldridgeLDN** [koyadovic/binance-rebalancing#1]
Firstly, thank you for creating this script.

I am trying to run the script for the first time but I am encountering the following error when running it

File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/binance/client.py", line 223, in _generate_signature
    m = hmac.new(self.API_SECRET.encode('utf-8'), query_string.encode('utf-8'), hashlib.sha256)
AttributeError: 'NoneType' object has no attribute 'encode'

This maybe a related issue, I wanted to get the script working first, but where would I specify my Binance API and secret? Should I create config file and store it there? 

I did read in the README.md file the need to specify the following:

## Environment variables
The default exchange implementation is for binance. This implementation need the following environment variables to be defined:

```bash
export BINANCE_API_KEY=<api_key>
export BINANCE_API_SECRET=<api_secret>

but wanted to check I'm following this right

**Comment by koyadovic** [comment]
Hi @TeldridgeLDN,

That problem is because they have not been defined as environment variables `BINANCE_API_KEY` and `BINANCE_API_SECRET`

If you are running the rebalances with `<project_path>/bin/rebalance.sh`, you can put your environment variables inside `<project_path>/.environment` file. Create it without problem. The `<project_path>/bin/rebalance.sh` script will test if this file exists, if so, it will execute it.

If you are running the rebalances with `python rebalance.py`, before, execute `source .environment`.

**Comment by koyadovic** [comment]
I mark this issue as closed.
